# Generated by Django 4.2.7 on 2023-11-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, upload_to='guide/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='guide',
            name='period',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
