# Generated by Django 4.2.7 on 2023-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_guide_image_guide_period_alter_guide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.URLField(),
        ),
    ]
