# Generated by Django 4.2.7 on 2023-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_remove_guide_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='delight_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
