# Generated by Django 4.2.7 on 2023-11-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_guide_delight_link_alter_guide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='tag',
            field=models.ManyToManyField(blank=True, to='guide.tag'),
        ),
    ]
