# Generated by Django 4.2.7 on 2023-11-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_category_guide_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
