# Generated by Django 4.2.7 on 2023-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='guide.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
