# Generated by Django 4.2.7 on 2023-11-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_alter_guide_tag_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='guide',
            name='tagtype',
            field=models.ManyToManyField(blank=True, null=True, to='guide.tagtype'),
        ),
    ]
