# Generated by Django 4.2.7 on 2023-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_tagtype_remove_guide_tag_delete_tag_guide_tagtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='tagtype',
            field=models.ManyToManyField(blank=True, to='guide.tagtype'),
        ),
    ]
