# Generated by Django 4.2.7 on 2023-11-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_alter_guide_tagtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='tagteam',
            field=models.ManyToManyField(blank=True, to='guide.tagteam'),
        ),
    ]
