# Generated by Django 4.2.7 on 2023-12-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Catagories'},
        ),
    ]
