# Generated by Django 4.2.7 on 2023-12-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_maincategory_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='teammatchingpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
