# Generated by Django 4.2.7 on 2023-12-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
