# Generated by Django 4.2.6 on 2023-11-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.RemoveField(
            model_name='users',
            name='registered_dttm',
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
