# Generated by Django 4.2.7 on 2023-11-27 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_users_options_remove_users_registered_dttm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='registered_dttm',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, verbose_name='사용자학번'),
        ),
    ]
